### ISSUE TITLE
Ozbib gives 7233 entries, exports 984 to bibtex

### ISSUE THREAD

**Issue by chirila** [clld/glottolog3#148]
https://glottolog.org/providers/ozbib metadata says there are 7233 entries, but when exporting using the download bibtex button, the file only contains 984 entries.

**Comment by xrotwang** [comment]
Yes, that looks like a bug. Generally, though, I'd recommend accessing the BibTeX of the reference providers directly in the data repository, e.g. https://raw.githubusercontent.com/glottolog/glottolog/v4.7/references/bibtex/ozbib.bib

**Comment by HedvigS** [comment]
Could that download button maybe be removed until the bug is fixed?

**Comment by xrotwang** [comment]
I made the (existing) link to the bibtex file on github more prominent and removed the BibTeX button from the table.

Downloads created on the fly - e.g. triggered by a button on a table - are limited to 1000 rows. And I guess this was further reduced to 984, because some ozbib records may have been merged into the same Glottolog reference.

**Comment by HedvigS** [comment]
> Downloads created on the fly - e.g. triggered by a button on a table - are limited to 1000 rows. And I guess this was further reduced to 984, because some ozbib records may have been merged into the same Glottolog reference.

Got it. it sounds like these on-the-fly downloads should maybe not be encouraged, or should have labels on them that it's not the full data set.
