### ISSUE TITLE
Re-activate langdocstatus browser

### ISSUE THREAD

**Issue by xrotwang** [clld/glottolog3#72]

**Comment by HedvigS** [comment]
Just... a general thumbs up and also a not to pushy question: were any of the comments and questions we had about GlottoVis answered?

**Comment by xrotwang** [comment]
Answered by whom? Or answered in code?
Am 02.04.2017 13:11 schrieb "Hedvig Skirgård" <notifications@github.com>:

**Comment by HedvigS** [comment]
Either, I haven't heard anything from anyone.

**Comment by HedvigS** [comment]
Oh, and then there was another message from them in 2016, asking for feedback again. I sent back basically the same comments as 2015.

**Comment by d97hah** [comment]
I've been communicating with them, I am up to date. But I am not sure what
information Hedvig is asking for.

2017-04-03 1:40 GMT+02:00 Hedvig Skirgård <notifications@github.com>:

**Comment by HedvigS** [comment]
Looking at Glottovis again now. I think it's great that Thom did this, it looks really cool! If this is gonna go on the site thought I think some things just need to be a bit clearer so it's useful to the general user of Glottolog. As usual, feel free to ignore my opinions. If you're thinking of launching Robert's browser instead, that feels a bit unfair to Thom, but I don't know your arrangements and plans.

About Glottovis:
* the clusters/sunbursts are very useful as they solve the known problem of ordering of dots. There needs to be some kind of pedagogical explanation of them and the colors though if people are going to take to it
* in general, there's a lot of smart things going on here, but since they're new they need to be explained.
* there's a legend for the colors for descriptive status and endangerment status, great! I didn't find this before, but it must have always been there.
* the buttons for stats per continent and time scale might need just simple labels for the axises so that it's easier to understand them right away
* possibility of making pacific centered by scrolling east/west
* a table displaying numbers of languages per description status and per endangerment level globally would be useful
* when you click a language, you get displayed the descriptive status but the endangerment status is not listed. it's obvious from the color, but maybe should be listed explicitly too
* Have it say Glottovis on the website and not just in the URL
* explain why some languoids are not shown (the "!" button)

(* extrawork that is way too late for: time slider that displays the world map and the languoids endangerment level and descriptive status at a certain point in time. This is the best feature of Robert's map, and it's really something people enjoy.)

Now, I don't know what you guys want from all of this. This is clearly a very useful function, but it's also a fancy fun visualisation function for the website and probably not part of the core functions of Glottolog (sharing the content and letting people do what they will with it). I probably care more about such things than you do, and you decide. Do with it as you will.

**Comment by HedvigS** [comment]
These suggestions of mine are basically all geared towards user-friendliness. There's nothing wrong with the basic underlying structure, and a smart person will figure it out. It depends on the intended audience and reach that you want for this part of Glottolog.

**Comment by HedvigS** [comment]
Oh noes... http://glottolog.org/langdoc/status/browser is down ;( ;(

**Comment by xrotwang** [comment]
http://glottolog.org/glottolog/language.map.html?country=PG#6/-6.235/149.747

**Comment by HedvigS** [comment]
Thanks Robert @xrotwang 

I was after the entire island, i.e. the indonesian side too. Ah, it's ok. We found another map.

**Comment by HedvigS** [comment]
Btw, I realise that rendering a map with all 8,000 dots is cumbersome. The other day on facebook, Claire was asking if there was such a map and today someone else asked for something similar. What I'm saying is it'd be a popular feature, if heavy and a bit superfluous to the core function of Glottolog.

**Comment by d97hah** [comment]
@Robert: I thought one can give in to demand and make Voronoi polygon based
maps, perhaps as part of Glottolog. For example, given a node, the
partition induced by its immediate children could be coloured. The bottom
node of glottolog (or some hypothetical version similar to it) would then
give the world family map. There's some version of the four-colour
problem to solve though (there are always heuristics and infinitely many
shades if nothing else) but with Voronoi regions many individual dots could
be reduced to a small set of polygons (usually one since (sub-) families
are often continuous) which would make it much less heavy on the browser
than 8000 dots. Have you ever pondered this?


2017-04-20 13:33 GMT+02:00 Hedvig Skirgård <notifications@github.com>:

**Comment by SimonGreenhill** [comment]
@d97hah -- I, @xrotwang and @LinguList were discussing this a few weeks ago, and @kirbykat did it last week for the DPLACE data. 

Nice and relatively simple visualisation, only concern is what to do with e.g. Polynesia, where the wide spread points of the Polynesian triangle will give a massive and overwhelming cell. Also assumes no overlaps, which is false, but unsolvable at the moment.

**Comment by d97hah** [comment]
And what if you just restrict the polygons to non-water territory?

2017-04-20 15:29 GMT+02:00 Simon J Greenhill <notifications@github.com>:

**Comment by xrotwang** [comment]
I think whether that will lead to better performance in the browser or not, is not completely clear to me. The dots are simple markers in Leaflet, which I guess the library is somewhat optimized for (considering it is the typical use case). Polygons on the other hand may be less optimized. The [345 eco regions in Tsammalex](http://tsammalex.clld.org/ecoregions) seem be a lot of work for the browser (although I admit that the Voronoi polygons will probably have a lot less points defining them).

**Comment by SimonGreenhill** [comment]
@d97hah -- well, I guess you're left with lots of empty water. It's such a nuisance that cultures are distributed evenly on the globe!

**Comment by HedvigS** [comment]
In the meantime, is is easy to render something like what was in the descriptive status browser but coloured by family?

**Comment by HedvigS** [comment]
Robert made a neat map for me with just language dots coloured by family, and permitted me to share it. Claire Bowern wrote back something relevant to this thread.

"Thank you Hedvig and Robert, this is great. We were talking about meshing this with the endangerment stats from ethnologue and endangeredlanguages.com. An effective (if simplistic) graphic might be to dyanmically fade the dots that are highly endangered.
Claire"

**Comment by HedvigS** [comment]
I think trying to show to many things at once in one map is not good, it makes it too busy. I like the coupling of endangerment and descriptive status, as in Robert's browser and Glottovis. I don't think it should be mixed with top-genetic unit.

**Comment by xrotwang** [comment]
The status browser is up again - with the same status as before, i.e. not fit for publication yet!

**Comment by d97hah** [comment]
And until it is, don't post url:s to it here...

2017-04-26 12:49 GMT+02:00 Robert Forkel <notifications@github.com>:

**Comment by HedvigS** [comment]
I keep it in my mind, and in my cookies. and nowhere else :)
